pipeline:
    build:
        image: golang
        commands:
            - go get github.com/pstuifzand/websub-hub/cmd/hubserver
            - go build github.com/pstuifzand/websub-hub/cmd/hubserver

    publish:
        image: plugins/docker
        repo: registry.stuifzandapp.com/websub-hub
        registry: registry.stuifzandapp.com
        secrets: [ docker_username, docker_password ]

    deploy:
        image: appleboy/drone-ssh
        host: hub.stuifzandapp.com
        username: hub
        secrets: ['ssh_key']
        script:
            - cd /home/hub/hub
            - docker-compose pull
            - docker-compose up -d

    done:
        commands:
            - ./deployment.sh
