pipeline:
    build:
        image: golang
        commands:
            - go get github.com/pstuifzand/websub-hub/cmd/hubserver
            - go build github.com/pstuifzand/websub-hub/cmd/hubserver

    publish:
        image: plugins/docker
        repo: registry.stuifzandapp.com/websub-hub
        registry: registry.stuifzandapp.com
        secrets: [ docker_username, docker_password ]

    # deploy:
    #     image: appleboy/drone-ssh
    #     host: publog.stuifzandapp.com
    #     username: publog
    #     secrets: ['ssh_key']
    #     script:
    #         - cd /home/publog/publog
    #         - docker-compose pull
    #         - docker-compose up -d
    #     when:
    #         event: deployment
    #         environment: production
